import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import { AuthProvider } from "@/components/AuthProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className=" max-w-4xl p-4 mx-auto">
          <AuthProvider>
            <Header />
            {children}
            <footer className="border-t mt-16 p-8þ text-center text-gray-500 p-8">
              &copy; 2024 All rights reserved
            </footer>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
